server.port: 8085

spring:
  redis:
    host: 10.10.80.11
    port: 7617
  kafka:
    bootstrap-servers:
      - "127.0.0.1:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: admin-consumer