server:
  port: 8088
spring:
  profiles:
    group:
      local: base-datasource, local-override
      dev: base-datasource
      prod: base-datasource
  main:
    web-application-type: REACTIVE
  main.allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  messages:
    basename: i18n/messages, i18n/messages_ko
    encoding: UTF-8
  thymeleaf:
      prefix: classpath:/templates/back_message/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      check-template-location: true
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml

logging:
  config: classpath:config/logback-spring.xml
  level:
    root: INFO
    okhttp3: OFF
  file:
    path: logs/back_batch

springfox:
  documentation:
    swagger-ui:
      base-url: /back_batch/api/docs
    open-api:
      v3:
        path: /back_batch/api/docs/v3/api-docs


cron:
  message-send: 0/10 * * * * ?
  craw-score: 0 */3 * * * ?
  craw-play: 0 */20 * * * ?
